remote_theme: daattali/beautiful-jekyll@master
plugins: 
  - jekyll-remote-theme

# Site info
title: Art2Artist Recognizer
description: An image classification API that classifies 20 famous artists' artworks
url: "https://naawshin.github.io"  #GitHub Pages URL
baseurl: "/Art2Artist-Recognizer"  #repository name

# Author info
author:
  name: Nowshin Tabasum
  email: "nawshintabassum88@gmail.com"
  github: naawshin

  

# Navigation bar
navbar-links:
  About Me: "aboutme"
  GitHub: "https://github.com/naawshin"


# Appearance
theme-color: "auto" 