
# Site info
title: Art2Artist Recognizer
description: An image classification API that classifies 20 famous artists' artworks
url: "https://naawshin.github.io"
baseurl: "/Art2Artist-Recognizer"

# Author info
author:
  name: Nowshin Tabasum
  email: "nawshintabassum88@gmail.com"
  github: naawshin

# Navigation bar
navbar-links:
  Home: ""
  Art2Artist App: "art2artist_recognizer"
  About Me: "aboutme"
  GitHub: "https://github.com/naawshin"

# Appearance
theme-color: "auto"